name: Build and Release macOS App
on:
  workflow_dispatch:
  
  push:
    tags:
      - 'release'

jobs:
  build_and_release:
    permissions:
      contents: write
    runs-on: macos-14 # macOS-latest is still macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build macOS App
        run: |
          xcodebuild \
            -project "Hidden Bar.xcodeproj" \
            -scheme "Hidden Bar" \
            -configuration Release \
            -archivePath "${{ github.workspace }}/build/Hidden Bar.xcarchive" \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS=""

      - name: Extract Unsigned App from Archive
        run: | 
          cd "${{ github.workspace }}/build/Hidden Bar.xcarchive/Products/Applications/" && zip -r "${{ github.workspace }}/Hidden Bar.app.zip" "Hidden Bar.app"
          ls -ale "${{ github.workspace }}/Hidden Bar.app.zip"
      #- name: Package App
      #  run: |
      #    xcodebuild \
      #      -exportArchive \
      #      -archivePath "$HOME/build/Hidden Bar.xcarchive" \
      #      -exportOptionsPlist exportOptions.plist \ # Replace with the path to your Export Options plist
      #      -exportPath $HOME/build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.event.head_commit.title }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ github.workspace }}/Hidden Bar.app.zip" # Replace with the path to your built app
          asset_name: "Hidden Bar.app.zip" # Replace with the desired name for the uploaded asset
          asset_content_type: application/octet-stream
